### ISSUE TITLE
AttributeError: module 'dlatk.lib.wordcloud' has no attribute 'tagcloudToWordcloud'

### ISSUE THREAD

**Issue by bonchae** [dlatk/dlatk#12]
The following code generates an error message. I am using dlatk-docker. Thanks.

```
dlatkInterface.py -d dla_tutorial -t msgs_my -c user_id \
-f 'feat$1to3gram$msgs_bchae$user_id$16to16$0_05' \
--outcome_table blog_outcomes  --group_freq_thresh 500 \
--outcomes age gender --output_name bchae_output \
--tagcloud --make_wordclouds

```

Error message:

```
outputting tagcloud to: my_output_tagcloud.txt
Traceback (most recent call last):
  File "/usr/local/bin/dlatkInterface.py", line 1834, in <module>
    main()
  File "/usr/local/bin/dlatkInterface.py", line 1346, in main
    wordcloud.tagcloudToWordcloud(outputFile, withTitle=True, fontFamily="Meloche Rg", fontStyle="bold", toFolders=True)
AttributeError: module 'dlatk.lib.wordcloud' has no attribute 'tagcloudToWordcloud'
```

**Comment by yoninachmany** [comment]
I am having the same issue.

**Comment by sjgiorgi** [comment]
We us an older version of wordcloud, please use version 1.1.3.
