### ISSUE TITLE
can not install dlatk

### ISSUE THREAD

**Issue by abdelhmead** [dlatk/dlatk#15]
$ dlatkInterface.py -d dla_tutorial -t msgs_xxx -c user_id --add_ngrams -n 1 2 3 --combine_feat_tables 1to3gram

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/env1/bin/dlatkInterface.py", line 4, in <module>
    __import__('pkg_resources').run_script('dlatk==1.1.6', 'dlatkInterface.py')
  File "/home/user/anaconda3/envs/env1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/anaconda3/envs/env1/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/home/user/anaconda3/envs/env1/lib/python3.5/site-packages/dlatk-1.1.6-py3.5.egg-info/scripts/dlatkInterface.py", line 21, in <module>
    from dlatk.classifyPredictor import ClassifyPredictor
  File "/home/user/anaconda3/envs/env1/lib/python3.5/site-packages/dlatk/classifyPredictor.py", line 37, in <module>
    from sklearn.decomposition import RandomizedPCA, MiniBatchSparsePCA, PCA, KernelPCA, NMF
ImportError: cannot import name 'RandomizedPCA'

**Comment by sjgiorgi** [comment]
This is a sklearn version issue. We use 0.18.2. I think RandomizedPCA was deprecated in 0.20.2. Try reverting to a previous version of sklearn.
