### ISSUE TITLE
issue with wordcloud.py

### ISSUE THREAD

**Issue by chagag** [dlatk/dlatk#29]
Hi, we recently tried to run ```--tagcloud --make_wordclouds \``` on our feature table. 

This is the full commend: 

```
python  ./dlatkInterface.py \
--corpdb NAME\
--corptable MSGS \
--correl_field user_id \
--host HOSTNAME\
--feat_table 'feat$1to3gram$msgs$user_id$16to16$0_05$pmi3_0' \
--outcome_table blog_outcomes --outcomes age gender \
--correlate --rmatrix --csv --sort \
--tagcloud --make_wordclouds \
--output_name ~/1to3gramsOcc05Pmi3_age_gender
```

We got the following error: 
```
Generating wordclouds using amueller's python package...
Traceback (most recent call last):
  File "./dlatkInterface.py", line 2129, in <module>
    main()
  File "./dlatkInterface.py", line 1611, in main
    wordcloud.tagcloudToWordcloud(outputFile, withTitle=True, fontFamily="Meloche Rg", fontStyle="bold", toFolders=True, metric=metric)
  File "/export/home/faculty/agoldenberg/dlatk/dlatk/lib/wordcloud.py", line 568, in tagcloudToWordcloud
    wordcloud(ngrams, freqs,output_file, colors, rgb=False, title=title, fontFamily=fontFamily, fontStyle=fontStyle)
  File "/export/home/faculty/agoldenberg/dlatk/dlatk/lib/wordcloud.py", line 256, in wordcloud
    mask=img_array).generate_from_frequencies(word_freq_tup)
  File "/export/home/faculty/agoldenberg/.conda/envs/dlatk/lib/python3.7/site-packages/wordcloud/wordcloud.py", line 401, in generate_from_frequencies
    frequencies = sorted(frequencies.items(), key=itemgetter(1), reverse=True)
AttributeError: 'list' object has no attribute 'items'```

This is likely caused by some issue with the module. Would love to get your help. Thank!

**Comment by sjgiorgi** [comment]
This has been fixed in the dev branch, which is very much ahead of public.  If you'd rather not switch to dev then you can easily modify line 256 in `dlatk/dlatk/lib/wordcloud.py` to

```
mask=img_array).generate_from_frequencies(dict(word_freq_tup))
```

i.e., add `dict` around `word_freq_tup`.

**Comment by chagag** [comment]
Thanks! We couldn't use dev but it work. I really appreciate it.
