### ISSUE TITLE
Connecting to MySQL

### ISSUE THREAD

**Issue by gserapio** [dlatk/dlatk#4]
It looks like I'm having trouble connecting to MySQL, since I set up a root password. Should I disable password access for my username, `gserapio`?

Here is the full traceback:
```
dlatkInterface.py -d dla_tutorial -t msgs_gsg -c user_id --add_ngrams -n 1 --feat_occ_filter --set_p_occ 0.001 --group_freq_thresh 500
/usr/lib64/python3.4/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/lib64/python3.4/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
matplotlib PdfPages or plt cannot be imported
pandas.rpy.common cannot be imported
/usr/lib64/python3.4/importlib/_bootstrap.py:321: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  return f(*args, **kwds)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'gserapio'@'localhost' (using password: NO)")
 (1 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'gserapio'@'localhost' (using password: NO)")
 (2 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'gserapio'@'localhost' (using password: NO)")
 (3 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'gserapio'@'localhost' (using password: NO)")
 (4 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'gserapio'@'localhost' (using password: NO)")
 (5 attempt)
 *MYSQL Connect ERROR on db:dla_tutorial
(1045, "Access denied for user 'gserapio'@'localhost' (using password: NO)")
 (6 attempt)
```

**Comment by sjgiorgi** [comment]
This could be a few things. I would first make sure:

1. You have read / write access on this database / table
2. You are able to connect without a password via the command line with something like `mysql -e 'select * from dla_tutorial.msgs_xxx limit 1'`.

For my setup I have a `.my.cnf` file in my home directory with my MySQL username and password:

` % less ~/.my.cnf`
`[client]`
`user=myusername`
`password=mypassword`

**Comment by gserapio** [comment]
Thanks for this! Sorry for the late response. I've been having MySQL issues on my VM all day. I can't log in as root anymore, even when I reinstall MySQL. I'll try these troubleshooting steps once I fix these MySQL problems.

**Comment by gserapio** [comment]
So I've been running this in Python 3, but MySQLdb keeps returning an import error: `ImportError: No module named MySQLdb`. I have it installed for Python 2.

When I run the dlatkInterface command above, I get this error:

```
$ dlatkInterface.py -d dla_tutorial -t msgs_gsg -c user_id --add_ngrams -n 1 --feat_occ_filter --set_p_occ 0.001 --group_freq_thresh 500
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/dlatkInterface.py", line 4, in <module>
    __import__('pkg_resources').run_script('dlatk==1.1.0', 'dlatkInterface.py')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mysqlclient' distribution was not found and is required by dlatk
```

When I append `python3` to the beginning of the command, I get this:

```
$ python dlatkInterface.py -d dla_tutorial -t msgs_gsg -c user_id --add_ngrams -n 1 --feat_occ_filter --set_p_occ 0.001 --group_freq_thresh 500
warning: wordcloud not found.
Traceback (most recent call last):
  File "dlatkInterface.py", line 22, in <module>
    from dlatk.semanticsExtractor import SemanticsExtractor
  File "/Users/myusername/Desktop/mpp_data/dlatk/dlatk/semanticsExtractor.py", line 14, in <module>
    from .featureExtractor import FeatureExtractor
  File "/Users/myusername/Desktop/mpp_data/dlatk/dlatk/featureExtractor.py", line 28, in <module>
    from .dlaWorker import DLAWorker
  File "/Users/myusername/Desktop/mpp_data/dlatk/dlatk/dlaWorker.py", line 3, in <module>
    import MySQLdb
ModuleNotFoundError: No module named 'MySQLdb'
```

[This StackOverflow thread](https://stackoverflow.com/questions/22252397/importerror-no-module-named-mysqldb) showed promise by offering an alternative to MySQLdb (since I think MySQLdb doesn't support Python 3). I tried replacing the `MySQLdb` import statement in `dlaWorker.py` with `import PyMySQL as MySQLdb`.

I will try replacing the import statements with either `PyMySQL` or `mysql` and update you on what happens. It might be cleaner to switch over to one of these two for full Python 3 support.

**Comment by sjgiorgi** [comment]
This is the package you need: https://pypi.python.org/pypi/mysqlclient

**Comment by gserapio** [comment]
Perfect—besides a few Python dependencies issues, I think it's mostly working now! Thanks a ton for your help.

**Comment by johezz** [comment]
@gserapio Hi! I was wondering how you fixed the Connect Error to MySQL? I had the exact same error messages as you.
