### ISSUE TITLE
ImportError: cannot import name 'RandomizedPCA' from 'sklearn.decomposition'

### ISSUE THREAD

**Issue by pnadelofficial** [dlatk/dlatk#49]
Hello,

I've been trying to install DLATK on my Mac M1, but I keep getting this error when I try to run STEP 1 - Feature Extraction of the tutorial: 

Traceback (most recent call last):
  File "/Users/pnadel01/miniconda3/envs/dla/bin/dlatkInterface.py", line 21, in <module>
    from dlatk.classifyPredictor import ClassifyPredictor
  File "/Users/pnadel01/miniconda3/envs/dla/lib/python3.10/site-packages/dlatk/classifyPredictor.py", line 37, in <module>
    from sklearn.decomposition import RandomizedPCA, MiniBatchSparsePCA, PCA, KernelPCA, NMF
ImportError: cannot import name 'RandomizedPCA' from 'sklearn.decomposition' (/Users/pnadel01/miniconda3/envs/dla/lib/python3.10/site-packages/sklearn/decomposition/__init__.py)

I would guess that the SKLearn version is wrong. I've been trying to downgrade from 1.2.0 to 0.18 but these installations won't work either. 

Let me know if there's any more information you need. 

Thanks,
Peter

**Comment by sjgiorgi** [comment]
I've updated pip, which should fix this issue. Can you try reinstalling via pip?
